baseURL = "https://tilcoding.com/"

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

# website title
title = "Today I Learned Coding"


# Author config
[author]
  name = "Today I Learned Coding"
  email = "tilcoding@gmail.com"
  link = "https://tilcoding.com"

# Language
defaultContentLanguage = "id"

# TimeZone
timeZone = "Asia/Jakarta"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

